# These pre-commit hooks don't ensure a passing CI run. Instead they act as
# a quick "smoke check" running static code analysis on the files changed.
# The hooks do NOT:
#     - Run tests or other time-consuming tasks.
#     - Check the whole codebase, just modified files.
#     - Run flake8 extensions.
#     - Allow mypy to look for missing imports (mypy runs with `ignore_missing_imports=True`).
repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.711
    hooks:
    -   id: mypy
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
