dist: xenial
language: python
python:
  - '3.7'
stages:
  - build
  - static-checks
  - test
jobs:
  include:
    - stage: build
      script:
        - python setup.py install
    - stage: static-checks
      script:
        - flake8 sire/ tests/ setup.py
        - mypy sire/ tests/ setup.py
        - black sire/* tests/* setup.py --check
        - isort -m 3 -tc -c sire/* tests/* setup.py
    - stage: test
      script:
        - coverage run -m unittest
        - coverage report
        - codecov
